//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int id_pedido { get; set; }
        public Nullable<int> cantidad_pedido { get; set; }
        public string descripcion_pedido { get; set; }
        public string direccion_pedido { get; set; }
        public Nullable<System.DateTime> fecha_pedido { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public string nombre_producto_pedido { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual proveedor proveedor { get; set; }
        public virtual producto producto { get; set; }
    }
}
